### ISSUE TITLE
Feature Request: Photos sorting

### ISSUE THREAD

**Issue by Scrambled777** [blissd/fotema#101]
Currently in all views, photos & videos are displayed in Oldest to Newest order.

It would be awesome if there are more sorting option. 

Personally, I would like to see Newest photos & videos first.

**Comment by blissd** [comment]
Hi @Scrambled777. Thanks for your feature request. Yes, something like this probably wouldn't be too hard to add, but it might need to wait until I finish off what I'm currently working on.

Do you think there would be an sort-order option in preferences that would affect all album views?
Or would it be settable per-album?
If per-album, do you think the sort-order would be remembered when Fotema is restarted?

**Comment by Scrambled777** [comment]
> Yes, something like this probably wouldn't be too hard to add, but it might need to wait until I finish off what I'm currently working on.

Take all the time you need mate. 

> Do you think there would be an sort-order option in preferences that would affect all album views? 

I think universal sort order in `Preferences` makes sense.

> Or would it be settable per-album? If per-album, do you think the sort-order would be remembered when Fotema is restarted?

How will this work? Is it going to be configured in `Preferences` or there will be an icon in header.

Or both of your presented solution could co-exists. 

Let's say there is universal sort order in `Preferences` which will affect all views. Then, if one wants to change sort order in particular Album, then can change from header sort icon.
![Screenshot_20240717_204315](https://github.com/user-attachments/assets/52b8b3ee-2e34-4aac-887c-8d3d496b6868)
It makes sense for Fotema to remember particular Album sort order on restart. Later on, if one again changes Universal sort order, then all other per album sort will reset to universal sort.
Does it makes sense?

PS: Can I raise more feature request? Not to pressurize you but, not to forget to raise them latter on.

**Comment by blissd** [comment]
Raise all the feature requests you want.

**Comment by Scrambled777** [comment]
@blissd, 

Thank you so much. Much appreciated.
