### ISSUE TITLE
Fotema crashes on startup

### ISSUE THREAD

**Issue by johannesboehler2** [blissd/fotema#108]
-Using the flathub version
-Ubuntu 22.04

It looks like there is something wrong in metadata.rs
```

(fotema:2): Adwaita-WARNING **: 14:49:03.500: AdwNavigationPage 0x642bba2a6a50 is missing a title. To hide a header bar title, consider using AdwHeaderBar:show-title instead.

(fotema:2): Adwaita-WARNING **: 14:49:03.500: AdwNavigationPage 0x642bba34c8a0 is missing a title. To hide a header bar title, consider using AdwHeaderBar:show-title instead.
thread '<unnamed>' panicked at core/src/photo/metadata.rs:93:75:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
```

**Comment by blissd** [comment]
Hi @johannesboehler2. Thank you for your bug report. I do indeed access an array without checking if it has a non-zero length on the reported line in metadata.rs. I'll added some checks and cut a new release soon.

**Comment by blissd** [comment]
I've released version 1.9.6 which should become available on Flathub later today. Please let me know if it fixes the bug you are experiencing.

**Comment by johannesboehler2** [comment]
Hi, thank you for the fix. I will check the release at evening.

**Comment by johannesboehler2** [comment]
Hi, I updated the app and now it works.
I have 6 photos with GPS, but the coordinates are not set. Maybe this was the problem.
Thank you for the new release!
Screenshot Loupe:
![Bildschirmfoto vom 2024-07-24 00-16-49](https://github.com/user-attachments/assets/ded5b9c7-27a5-4ab6-83f7-68e2f2c1fdf2)
