### ISSUE TITLE
"Mobile" and "Desktop" face detection options are confusing

### ISSUE THREAD

**Issue by blissd** [blissd/fotema#139]
In issue #138 user @forteller commented that the Mobile and Desktop face detection options are confusing, and they are quite right. These options should be better explained or renamed to be more obvious as to what they mean.

For reference:

"Enable for mobile" means use two BlazeFace models (I think one trained on a phone's rear camera and another trained on the selfie camers)f to detect faces. BlazeFace is a light weight face detection model designed for mobile devices so is relatively fast, but the trade off is that it misses lots of "obvious" faces, especially if the face is relatively large in the photo.

"Enable for desktop" means use a MTCNN face detection model, which is about four or five times slower then the two BlazeFace models, but produces much better results. As far as I can tell, it matches almost all faces I would expect it to match, but the trade off is that is takes a long time to run over a large photo library.

If you select one model and then change your mind, then you can't easily tell Fotema to reprocess already processed pictures with the new model. This is only really important if you started with the mobile models and then switched to the desktop model to detect more faces. You can ask Fotema to re-scan individual files, but now all previously processed files.

Some options:

1. Drop the choice selection and just use the MTCNN/Desktop model for better, but slower, face detection.  And maybe figure out GPU acceleration?
2. Drop the MTCNN model and figure out how to tune the faster BlazeFace model for more face matches?
3. Add better explanations of the different options.

**Comment by blissd** [comment]
Hmm... turns out the BlazeFace model has  a `target_size` parameter which influences what size of face is detected by the model.

**Comment by forteller** [comment]
Hey, really appreciate this great follow up of my issue!

I'm thinking two things here:

1. Yes, it seems good to give people these options between fast/medium quality and slow/good quality, but then just talk about the options like that. There's no need, I think, to say who should choose what. Just ask do you want the better, slower option or the less accurate, faster option? This choice is not totally uncommon, I think.
2. I do think that you can safely turn up the minimum size of faces detected. I had this screenshot where my profile image was just a tiny thing in the corner, and Fotema picked it up as my face. Yes, it was my face, but it was so tiny! I don't think it's realistic that most people would need so small faces to be detected. :)
3. Also maybe you should be able to blacklist some folders before starting the scanning. For example I fear that scanning my screenshots folder will give me a ton of faces in the People pane that are just random people from news articles etc I've taken a screenshot of :)

**Comment by blissd** [comment]
I've experimented with using several BlazeFace models and the results look promising.

*Reference Timings*
Face detection using Fotema 1.10.0 using the "desktop" mode.

13,699 photos. 140 minutes. 21,391 faces detected.

*Three BlazeFace Models*
Face detection using three BlazeFace models, each tuned for a different face size.

13,699 photos. 55 minutes. 17,148 faces.

Note that in each case a number of detected faces will not actually be faces.
