### ISSUE TITLE
GitHub Action Flatpak build fails by running out of diskspace

### ISSUE THREAD

**Issue by blissd** [blissd/fotema#142]
The GHA builds for Fotema are failing with an error that looks like the build is using all the diskspace. I've had a go using some methods for "reclaiming" diskspace in the GHA builds, but they had no effect.

As far as I can tell, GHA runners have 14GB of usable diskspace. Looking at the build directory on my dev laptop, I see Fotema is using about 17GB... which sounds like a lot to me.

I'd really like the GHA Flatpak build to work, either by somehow freeing up more diskspace, or by modifying the build to use less diskspace.

**Comment by fiftydinar** [comment]
Have you tried using `jlumbroso/free-disk-space@v1.3.1` action?

**Comment by blissd** [comment]
I haven't tried that one exactly, but I did try the fork at [ insightsengineering/disk-space-reclaimer
](https://github.com/actions-marketplace-validations/insightsengineering_disk-space-reclaimer)

https://github.com/blissd/fotema/commit/0ad4a7188f0e9817a86469cbe2169906eb394b33

**Comment by blissd** [comment]
Inexplicably, my last few PRs have built successfully without my making any changes. If that continues, then I'll close this issue.
