### ISSUE TITLE
Suggestion: Fotema flatpak warning when `xdg-pictures` can't be found

### ISSUE THREAD

**Issue by CocolinoFan** [blissd/fotema#164]
Hello,

If this is easy to do, it my be worth it.
Right now if you install Fotema flatpak and you don't have the `xdg-pictures` directory setup or is deleted, Fotema will just not launch. For me it shows the load screen and then stops. Very mystifying for an average user.
Yep, fixing your `xdg-pictures` directory will fix the problem.
But maybe Fotema should display a warning to the user as to what is going wrong. Something like "Fix your `xdg-pictures` you big dummy!"

**Comment by blissd** [comment]
Hi @CocolinoFan.

You're right... that doesn't sound like a great user experience. I'd like to get rid of the static permission for the xdg-pictures directory and instead have the user select where their pictures directory as part of an initial setup step, which would fix this problem.
