### ISSUE TITLE
Remove  Flatpak "filesystem=xdg-pictures:ro" permission

### ISSUE THREAD

**Issue by blissd** [blissd/fotema#165]
Fotema's Flatpak manifest includes the following "static" permission:

```json
    "--filesystem=xdg-pictures:ro",
```

This allows Fotema to automagically discover the user's pictures directory (commonly at `~/Pictures` for English speakers) so users can view their picture library without needing any setup or configuration.

However, this static permission is not entirely satisfactory.:

1. Much to my chagrin, the static permission causes the GNOME Software app to mark Fotema as "Potentially Unsafe". I believe that for Flatpak apps static permissions are frowned upon and should be replaced with "dynamic" permissions where the user grants the permission at runtime.
2. One or two users have raised tickets requesting to be able to select a picture directory other than xdg-pictures for reasons that are perfectly valid (see #18). A vanity search for Fotema also reveals grumbling and complaints about the absence of this functionality.
3. User @CocolinoFan has pointed out that if the user hasn't configured an xdg-pictures directory, then Fotema can fail to start (see #164).

I would like to remove the static permission and replace it with a dynamically granted file system permission for the user's picture library root, with the following caveat: my primary goal is to remove the static permission, not simply to add the feature to select which directory Fotema will scan for pictures and videos. Consequently, I don't want to add a broader permission to allow the user to select any directory (such as `--filesystem=host:ro` or `--filesystem=home:ro`).

I think the [XDG Documents Portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Documents.html) could work for dynamically granting permanent access to a directory.

The XDG documents portal presents a file chooser to the user who can then select a file that will subsequently be mounted in the Flatpak's sandbox under `/run/user/$UID/doc/`. I don't know if this also works for directories or just individual files, so I'll have to try it out.

File system paths mounted by the XDG Document appear to be permanent (and can be listed with `flatpak documents --columns=all`--much to my surprise I had over 800 documents listed!), but I've seen a comment that exposing directories through the portals is "[unreliable](https://discourse.gnome.org/t/gnome-application-settings-should-include-flatpak-permissions/12359/3)" in some unspecified way.

Some XDG documents portal trade-offs:

1. When Fotema's UI shows the library root it will start with `/run/user/...`, which is both ugly and confusing. I've seen one or two Flatpaks present paths to me like that after I've selected a file, and before I was more familiar with Flatpak I found it very unintuitive and confusing. Even now with a better understanding I still dislike it.
2. Fotema has a feature for opening the containing folder of a picture or video in the user's file manager, but I think that will break if Fotema doesn't have access to the true path of the file.

Allowing the selecting of the picture library root will require a setup page when Fotema is first run, so that the user can select where their pictures are. There will also have to be a setting in the application preferences to allow the library root to be changed. However, changing the library root will have the (possibly expensive) consequence of Fotema deleting all the generated thumbnails, transcoded videos, and detected faces, only to then create new thumbnails, etc., for the new library root.

Comments and suggestions are welcome.

**Comment by forteller** [comment]
Sounds good!

You could use a welcome screen like this for the initial setup https://github.com/amit9838/mousam/issues/156
