### ISSUE TITLE
Mystery photo parameter "File Created"

### ISSUE THREAD

**Issue by CocolinoFan** [blissd/fotema#167]
Hello.
What does this `File Created` parameter represent?
It looks like Fotema is ordering pictures based on that.
I tried changing it with `touch -a -m -t` command, no luck.
```
file 05-05-2017-Kuro-Coventry.jpg 
05-05-2017-Kuro-Coventry.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, datetime=2017:05:05 00:00:00], baseline, precision 8, 1080x1920, components 3
```
![2024-08-24-194644](https://github.com/user-attachments/assets/361ee942-d6d4-465b-a0f6-9b7def6ad862)

**Comment by blissd** [comment]
Hi @CocolinoFan.

File created should be the file creation date from the file metadata. As for ordering photos in the album views, Fotema tries several dates, preferring dates from EXIF metadata over file system metadata. You can see the rules in the visual view SQL:

```sql
COALESCE(
    pictures.exif_created_ts,
    videos.stream_created_ts,
    pictures.exif_modified_ts,
    pictures.fs_created_ts,
    videos.fs_created_ts,
    pictures.fs_modified_ts,
    videos.fs_modified_ts,
    CURRENT_TIMESTAMP
  ) AS ordering_ts
```

**Comment by CocolinoFan** [comment]
Thank you sir. 
Sorry, but I am going crazy. This is the picture (metadata and all):  https://github.com/user-attachments/assets/fa41d23b-ed1a-45ae-8b04-4a3136b4cf2c
All the metadata I can find (EXIF, IPTC, XMP) says it was made in 2017, but nonetheless picture gets sorted at the top of the gallery.
Maybe Fotema sorts the pictures based on EXIF metadata at first, but if the metadata changed (I manually change it), Fotema doesn't recheck 🤔.

**Comment by blissd** [comment]
I dropped your picture in my library and it shows up on May 5th 2017, which matches the EXIF metadata.

Hmm... I think you are right that Fotema doesn't rescan metadata at startup, unless I've incremented a metadata version flag indicating that Fotema is capable of extracting new metadata from images.

To force Fotema to update the metadata, move the photo out of your library, restart Fotema so it performs a cleanup which will clear the photos data from the data base, exit Fotema, put the photo back, and start Fotema again.

Sorry that is a bit convoluted. Perhaps Fotema needs a button to rescan metadata for either an individual photo or the whole library.

**Comment by CocolinoFan** [comment]
Yep thank you, this worked 🙏: removing photo from the directory, open Fotema, close Fotema, move photo back in the directory and re-open Fotema.
It is a bit convoluted but the procedure makes sense. 
I always like new features :D but honestly I don't know how many people would use this. Editing photos metadata is something you do once, this things should be automatic.
