### ISSUE TITLE
Still recognizing faces after turning it off

### ISSUE THREAD

**Issue by forteller** [blissd/fotema#178]
Hi. Still loving this application, and very happy to see you working actively on it!

I have this issue now where when I open it up it starts the face recognizion work, even though I have turned that off in the settings. I've tried turning it on again and back off again, but that does not help. I have the latest version from Flathub. Let me know if you need any more info. Thanks! :)

**Comment by blissd** [comment]
Hi @forteller, I'm glad you are enjoying Fotema. I'm still plugging away, but soon my work situation will have a significant change so I'll have more demands made on my time.

Hmm... I see that when face detection is disabled in the preferences, detecting new faces is disabled but scanning new photos to detect people is still enabled. Does the activity banner say "Detecting faces in photos..." or "Recognizing people in photos..."?

**Comment by blissd** [comment]
Something I'd like to do with the face detection option to disable face detection is to have separate options for disabling the slow face detection process and showing the people album. I think it might be nice to disable detection, but keep the people album.

**Comment by forteller** [comment]
It says "Recognizing people…"

Yes, I think it would be good to be able to keep the already generated people albums even if you turn off detection in new photos.
