### ISSUE TITLE
allow unlimited sizing of the fotema window

### ISSUE THREAD

**Issue by MariahWest01** [blissd/fotema#190]
i use my linux tablet at 300% scale so fotema takes 1/3 of my screen. i'd want to resize the window to be smaller but it won't

**Comment by blissd** [comment]
I don't think a allowing unlimited resizing makes sense, as there is definitely a practical limit as to how narrow the window can be while remaining visually appealing and useful. However, if you have a suggested minimum width below the current 360 points, then I can take a look.

For reference, I have taken the minimum of 360 points from the [GNOME human interface guidelines](https://linuxphoneapps.org/docs/resources/developer-information/#hardware-specs-to-consider).

**Comment by MariahWest01** [comment]
![Screenshot_20240910_223837](https://github.com/user-attachments/assets/31f0722b-39d5-43e2-acc0-9efe44946c53)
for example qview is the size i want. as i usually have fotema opens its annoying how big it is. i know it is smaller at 100% scale but i have bad motor control. maybe have a option to scale the ui independent of global scale?

**Comment by blissd** [comment]
I've had a test with a width of 240 points, which allows for two columns of photos in the album views, and also 184, which allows 1 column of photos. Any lower than a width of 184 results in some warnings being printed when resizing the window and starts to obscure the day/month/year buttons.

I think 184 points is probably closer to the qview width you show above, but it comes at some cost in Fotema. All the album views become can only accommodate one column of photos, which I think is fine for the year and month views as they use a larger thumbnail dimension to allow more space the overlayed text, but it doesn't look great on the day view which uses a smaller thumbnail size on narrow devices. More annoyingly, it becomes impossible to dismiss the slide-over side navigation bar with the mouse (though the escape key still works).

If the sizes in the screenshots below look fine to you, then I'm happy to cut a release with a minimum width of 240 points.

![Screenshot from 2024-09-11 07-31-45](https://github.com/user-attachments/assets/00171a5b-14e3-4f76-9dc8-40ab2af361a8)
![Screenshot from 2024-09-11 07-29-30](https://github.com/user-attachments/assets/9e8d7267-9072-4668-804a-e25d7742ad88)

**Comment by MariahWest01** [comment]
yes it does. can the height be smaller too?

**Comment by blissd** [comment]
> yes it does. can the height be smaller too?

The screenshots I took don't show the minimum height (294 points). When resized to the minimum, it is less than two thumbnails tall (plus navigation button at the bottom of the window), so I don't think I can really make it any shorter than that.

**Comment by MariahWest01** [comment]
ok. thanks

**Comment by blissd** [comment]
I've cut release 1.14.1 with a new minimum width of 240 points, which should be available on Flathub later today.

**Comment by MariahWest01** [comment]
pictures doesnt scale to the size, instead get cut off 
![Screenshot_20240911_132823](https://github.com/user-attachments/assets/b4dae084-e5d7-4441-841c-bc7e57b5863d)

**Comment by blissd** [comment]
Unfortunately that is true. Zooming and scaling is one of Fotema's missing features :-( I have to admit I don't notice it too much as I use Fotema at a pretty large size, but that is definitely a feature that should be added.

**Comment by MariahWest01** [comment]
will there be zoom buttons as opposed to pinch gestures or scrollwheel?

**Comment by blissd** [comment]
I would hope to support both buttons and gestures.

**Comment by MariahWest01** [comment]
will the buttons appear on a touchscreen

**Comment by blissd** [comment]
I've not designed or coded anything towards this yet, but yes, I would hope so. However, I would want the buttons to fade away after some period of no user interaction and pop back on a mouse jiggle or screen touch.

**Comment by MariahWest01** [comment]
i would like that. can the face icons on pictures be toggled? i currently have face reconization off as i just want the picture

**Comment by blissd** [comment]
Yeah... I also don't want the pictures to be overlayed all the time. I don't know quite how I want it to work yet. Might be that the face icons are only visible when the info-bar is displayed, or might be something else.

**Comment by MariahWest01** [comment]
ya. can u add a pitch black theme?
