### ISSUE TITLE
[Proposal] Better app icon

### ISSUE THREAD

**Issue by rene-coty** [blissd/fotema#23]
While the app icon is sufficient to understand what it does and its purpose, it remains only a big symbolic on a gradient, which can look a bit out of place on certain desktop environments.

Many other apps that rely on the GNOME components / libadwaita style use more elaborated icons (colorful, with simple geometric shapes, while having a solid metaphor - you can find guidelines on how to create great icons [here](https://developer.gnome.org/hig/guidelines/app-icons.html)).
If you're not feeling comfortable with icon design, don't hesitate to get in touch with GNOME designers [here](https://gitlab.gnome.org/Teams/Design/app-icon-requests/-/issues) by filling an icon request; I'm sure they'll be glad to help!

This is just a simple feedback from my user experience with Fotema - feel free to reject it, otherwise I'm glad someone could manage to build a replacement for gnome-photos :)

**Comment by blissd** [comment]
Thank you for your feedback. I agree the icon design falls short... but that is what you get when the icon's creator is a programmer, not a designer. At some point I'll look into designing a new icon that is more inline with modern sensibilities.
