### ISSUE TITLE
Fotema's initial launch screen is confusing

### ISSUE THREAD

**Issue by rzeigler** [blissd/fotema#236]
When I first launched Fotema (installed from flathub version 1.15.0) I was greeted with this screen.

![image](https://github.com/user-attachments/assets/c4f23de5-593c-41ba-85d3-1865287a8d88)
 
Because the select directory button is below the fold of the scrollbar I initially thought that I was supposed to drag and drop a folder onto the window. It was only incidentally that I thought of scrolling because the content looks perfectly sized to the window. The scrollbar is very very subtly visible so I didn't notice it initially.

Fotema should probably either size itself slightly larger or do something to indicate scrolling is needed to reveal the button.

**Comment by blissd** [comment]
Thanks for the bug report, @rzeigler. Well, that's an embarrassing start for Fotema! I'll have a look at making the default window slightly taller so the button is visible.
