### ISSUE TITLE
View next/previous with arrow keys

### ISSUE THREAD

**Issue by forteller** [blissd/fotema#237]
I was sure there was an issue for this already, but now I can't find it.

My biggest wish for Fotema right now is to be able to go to the next/previous image/video with left/right arrows.

Thanks! :)

**Comment by blissd** [comment]
Hi @forteller. I would like this to so it is pretty high up on my list of things to do.

**Comment by blissd** [comment]
This feature is in v1.17.0 which is now available on FlatHub.
