### ISSUE TITLE
Viewing a motion photo (Animated) increases RAM usage untill device crash

### ISSUE THREAD

**Issue by CocolinoFan** [blissd/fotema#239]
Hello,
I am not sure if is v1.15.0 or v1.15.1 that introduced this bug. But, when viewing a Animated/Motion photo the RAM usage will increase until there is no more and the device freezes dead.
I have tested on my Librem 5 running PureOS and on my computer running Kubuntu 24.04

P.S. Before this update Animated/Motion photos were very laggy on my Librem 5. But, after this update they play smoothly, very nice.

**Comment by blissd** [comment]
Hi @CocolinoFan, thanks for this bug report. I can confirm that I can reproduce this by viewing motion photos, too.

I don't know why this has changed! I haven't put in any work around motion photos or video playback, so I'm not sure how this memory leak snuck in. Perhaps it is related to upgrading to the GNOME 47 runtime?

In my testing pausing the motion photo stops Fotema from consuming more memory, but doesn't free the memory already consumed.

I also observe that when I play back a non-motion photo video that memory creeps up during playback and does not free either.

I'll have to investigate further, I'm afraid.

I'm glad that motion photo playback is smoother for  you--but I didn't do anything! Probably a side-effect of upgrading the Flatpak runtime to GNOME 47.

**Comment by blissd** [comment]
I have tests the commits one by one, and it is this commit for bumping the runtime to GNOME 47 (plus updating some dependencies) that is the culprit -> https://github.com/blissd/fotema/commit/c58be6cb910148c2c4b71d6718edc1eea2f6573b

**Comment by blissd** [comment]
Rolling back the Flatpak runtime to GNOME 46 fixes the problem for me. I've triggered the process for cutting the 1.15.2 release which should be available on Flathub in a few hours.

**Comment by CocolinoFan** [comment]
For me too, v1.15.2 fixed the RAM usage but, I am back to laggy/stuttery motion photos on my puny Librem 5. Eh, so is life.

**Comment by blissd** [comment]
I've tried using the GNOME Builder leak detector, but I don't really understand what I'm looking at and from what I did see, nothing jumped out at me.

I've had a go rewriting the video viewing code to use gtk::Video instead of gtk::Media file, and that does fix the memory leak... but replaces it with other problems. Either running out of GPU memory which is triggered after swiping between several videos, or having a vulkan error,  or by running out of file handles (if I switch the render to GL), which I think is from MESA shader cache files.

**Comment by blissd** [comment]
Hmm... I wonder if it is related to this bug? https://gitlab.gnome.org/GNOME/gtk/-/issues/7013

**Comment by blissd** [comment]
Through Flathub I've received updates to `org.gnome.Sdk//47` and `org.gnome.Platform//47`, and it looks like that might have fixed the memory leak.

**Comment by blissd** [comment]
@CocolinoFan Fotema v1.15.3 is now available on Flathub using the GNOME 47 runtime. Looks good to me, but do let me know if the memory leak persists for you.

**Comment by CocolinoFan** [comment]
v1.15.3 works great on all my devices as well, no memory leaks.
With this update I have buttery smooth Animated photos on my Librem 5 as well 🥳
