### ISSUE TITLE
Fotema's min-width is slightly too wide for good mobile support

### ISSUE THREAD

**Issue by 1peter10** [blissd/fotema#28]
Hi, thank you for creating this awesome app, it's really delightful!

Unfortunately, it's still a bit too wide for Linux Mobile devices (see screenshots below); the recommended width for these is 360px, as described here: https://developer.gnome.org/hig/guidelines/adaptive.html 

This also fits the common devices well: https://linuxphoneapps.org/docs/resources/developer-information/#hardware-specs-to-consider

I'll be happy to help with testing 🙂

Screenshots:
![fotema-1](https://github.com/blissd/fotema/assets/32742559/1b98f588-1cb9-43eb-ab6b-b2338365ff02)
![fotema-2](https://github.com/blissd/fotema/assets/32742559/7d65f874-cbf7-414d-b318-d1bf88bff835)

**Comment by blissd** [comment]
Thank you for your feedback. I'm excited to see Fotema on mobile as I would like to use a Linux on a mobile device one day. I have tried to use the GNOME/Adwaita functions to support mobile devices, but it is hard to tell how successful I've been without a device to test with.

AT somepoint I'll update the minimum width to be 360px and will update this issue when it is released. 

I'm be curious to hear what other changes would be necessary to make Fotema work better on mobile, such as perhaps having smaller thumbnails when on a narrow display.

**Comment by blissd** [comment]
@1peter10 Fotema 1.5.0 is now available on Flathub. I've adjusted the minimum width and height to match the GNOME suggestions and have added what I hope are quality of life improvements for narrow displays.

**Comment by 1peter10** [comment]
Thank you so much, it fits the screen now :-) Awesome work!
