### ISSUE TITLE
"Library" photo thumbnail is in worse quality than "Folders" photo thumbnail

### ISSUE THREAD

**Issue by fiftydinar** [blissd/fotema#31]
Here are the screenshots which demonstrate the title of the issue.
Open the screenshots & quickly switch between them, to notice the difference.

Thumbnail in "Folders" is a bit larger, so that probably also affects how the thumbnail is going to be scaled.

"Library":
![Screenshot from 2024-05-21 21-16-44](https://github.com/blissd/fotema/assets/65243233/59339d8d-06d5-4da5-a98f-0b87ed94b7fb)

"Folders":
![Screenshot from 2024-05-21 21-16-48](https://github.com/blissd/fotema/assets/65243233/d70dcf76-4d37-4754-97e1-da67f41972d4)

**Comment by blissd** [comment]
Hi fiftydinar. Thanks for taking the time to produce screenshots for your bug report. Both pages use the same thumbnail image and both should configure the thumbnail to be 200x200 when displayed. I'm not really sure how to fix the minor size different, but I am currently trying to redo how the grid widgets are configured in the different album types (as behind the scenes they are not entirely consistent), so maybe that will fix size difference as a happy side-effect.

**Comment by blissd** [comment]
I think this is fixed in the latest release.

**Comment by fiftydinar** [comment]
I confirm it is, thanks!
