### ISSUE TITLE
Clicking on menu button in sidebar causes it to close in the mobile view

### ISSUE THREAD

**Issue by knuxify** [blissd/fotema#49]
In the mobile view (when the window is below a certain width), clicking on the menu button in the sidebar makes the popup appear, but also makes the sidebar close. Video of the issue:

https://github.com/blissd/fotema/assets/23167991/c43be974-74e7-40dd-b62f-862488d2dbe5

Running Fotema 1.7.0 from Flathub.

**Comment by blissd** [comment]
Hi @knuxify. Thanks for your bug report and the video that shows what is happening. I can confirm that I can reproduce this behaviour and will see if I can figure out what is going on.

**Comment by blissd** [comment]
I understand the problem and it will be fixed in the next release of Fotema.

**Comment by blissd** [comment]
Fixed in v1.7.1 which is now available on Flathub.
