### ISSUE TITLE
Thumbnails are not created

### ISSUE THREAD

**Issue by johannesjh** [blissd/fotema#61]
Hi David, thank you for building v1.8.1. where photos without file creation date are now successfully indexed. This is working now. But there is another problem: The thumbnails are not generated.

I installed fotema v1.8.1 from flathub. I first removed all of fotema's files by deleting `~/.var/app/app.fotema.Fotema`. I then started fotema as shown in the log. 

[log.txt](https://github.com/user-attachments/files/15685434/log.txt)
![image](https://github.com/blissd/fotema/assets/581188/33baa362-f2c8-4d87-b66d-7376482b67e3)

from how I interpret the log, it appears that fotema did find the photos (`Found 36995 photos to add to database`), but then failed to generate thumbnails for these photos (`Found 0 photos to generate thumbnails for`)

**Comment by blissd** [comment]
I was really hoping you'd get to see some photos in Fotema!

Hmm... there are a few places that could be causes of the problem. If you look in the pictures table of the database is the 'is_broken' column set to '1'? If so, then the pictures are considered corrupt or unsupported in some way and will be excluded from future processing. Currently the is_broken column is set when thumbnail generation fails for a photo.

If is_broken is '1', then you might want to clear out all the Fotema data and run again and see if any errors are logged when trying to generate thumbnails.

**Comment by blissd** [comment]
Hmm.. actually, if photos are marked as broken then they won't show up in the photo grid like your screenshot shows.

**Comment by blissd** [comment]
Do you see anything in the thumbnail cache directories? They are under `~/.var/app/app.fotema.Fotema/cache/app.fotema.Fotema/photo_thumbnails`.

**Comment by blissd** [comment]
Do you see anything in the thumbnail cache directories? They are under `~/.var/app/app.fotema.Fotema/cache/app.fotema.Fotema/photo_thumbnails`.

**Comment by blissd** [comment]
If a photo file format isn't directly supported by the Rust `image-rs` library then I fallback to using Glycin to convert the image so a thumbnail can be generated. Do you see anything if you start from scratch with the glycin logs switched on? `glycin=info`

**Comment by blissd** [comment]
I think I understand the problem and it is related to my previous fix for creation times.

**Comment by blissd** [comment]
I have a fix on this branch -> https://github.com/blissd/fotema/pull/62

**Comment by blissd** [comment]
Fix is in release 1.8.2 which is now available on Flathub.

**Comment by johannesjh** [comment]
It is working now, awesome!! Thank you, David!
