### ISSUE TITLE
Design a new app icon

### ISSUE THREAD

**Issue by blissd** [blissd/fotema#88]
Fotema has a pretty generic icon that does not comply with [GNOME HIG icon standards](https://developer.gnome.org/hig/guidelines/app-icons.html). This causes Fotema to fail the icon review step on Flathub which prevents Fotema from being considered as an "app of the day" (I think?), and has raised a number of comments as to its not being good enough.

I agree! The icon should change, but I'm not sure to what. Here are some thoughts on what I like in icons (in no particular order):

1. Pretty. Not too busy.
2. Some colour (preferably colours that work well with the light/dark banner theming on Flathub). Easy to see on a variety of backgrounds.
3. Joyfulness and playfulness. Looking at you [YMuse](https://flathub.org/apps/com.yktoo.ymuse).
4.  Iconography that makes me think of photos. I do like the photo app icons that use a Polaroid style photo (like in #83 and [Loupe](https://flathub.org/apps/org.gnome.Loupe), but I wouldn't say that is a requirement.

Some icons I like from other apps (also in no particular order):

YMuse, [KDE Photos](https://flathub.org/apps/org.kde.koko), Loupe, Newsflash, Shortwave, Tuba, Iotas.

Some ideas:

1. Something you would actually photograph in a Polaroid photo or a traditional photo frame, like a stylized flower, a man and his dog, a pet by itself, and so on.
2. Something that suggests photo albums. A book of photos? A stack of photos?
3. I see my ideas are pretty derivative of existing photo app icons... so perhaps something entirely new?

**Comment by drpetrikov** [comment]
what about an icon similar to elementary's? i've made a draft too, the bottom photo would be more tilted to make the "stack" effect more pronounced
![image](https://github.com/blissd/fotema/assets/160746431/85a9cfd0-f79a-49c4-972a-d8296d6b941d)
![image](https://github.com/blissd/fotema/assets/160746431/3a9a041a-640b-431b-85e9-5695a3ada5ae)

**Comment by drpetrikov** [comment]
i could use microsoft's open source Fluent Emoji as they're beautiful and have depth and shadow

**Comment by drpetrikov** [comment]
i've made some drafts of what could the "inside" of the photo look like![image](https://github.com/blissd/fotema/assets/160746431/26fcd383-bcb3-4a40-b5cc-cdaaa6b4b07c)![image](https://github.com/blissd/fotema/assets/160746431/713589e7-9289-4bc5-a295-037454157d3b)

**Comment by drpetrikov** [comment]
@blissd what do you think?![image](https://github.com/blissd/fotema/assets/160746431/0f784b3a-5137-4cbb-be71-f5bb603820e3)

**Comment by blissd** [comment]
I like the stack effect.

**Comment by drpetrikov** [comment]
is it good enough? i'm going to tweak it a bit more

**Comment by fabiscafe** [comment]
I think this is to close to loupe to be an original brand icon.
![grafik](https://github.com/user-attachments/assets/339b1435-2c91-4aca-bf9f-6257122fee38)

I was thinking about another direction, like
![grafik](https://github.com/user-attachments/assets/b88b6e7d-b156-4f52-823a-1a6e82cb6022)

Where the photo content jumps out of the frame showing the fun in photography, you have multiple elements, as its normally what you have in a gallery and a colorful line, that represents time. Absolutely not finished but I like the general direction.

The problem with such an approach is that it might be just to much. So we might have to thinker a little more.

**Comment by blissd** [comment]
There is a lot to like here. The stack looks good and the fish breaking out of the photo frame is nice and playful. However, I think the multi-colour strip on the left gets lost as a detail as the icon becomes smaller, and to my eyes I have a similar problem with the fish losing detail on the 32x32 size and looking like something else.

**Comment by fabiscafe** [comment]
:smile: I actually don't like the fish in this context at all, as it looks very alien compared to everything else. It was just some asset I had available to show what I meant. Losing details is very OK, I think. You get to know the app with the bigger icon 64-128 variants. I made the multi-colour strip by design relatively bright. So it will appear to disappear on smaller resolutions without trying to hard to stay visible or to distract much. 
Without it I felt something was missing, and made it look like a tablet, not a foto frame or app-window: 
![grafik](https://github.com/user-attachments/assets/a73e15de-2432-4cac-942e-27ad0b98987c)

Of course everything needs more fine-tuning - the same as for the shadow parts. They are way to dark right now.

To toy around with, here is the source:

![app fotema Fotema Source](https://github.com/user-attachments/assets/0391043b-a050-43de-bd14-ffe145676a08)
(License: CC BY-SA 4.0)

**Comment by blissd** [comment]
> 😄 I actually don't like the fish in this context at all, as it looks very alien compared to everything else.

Yes, it is tough to figure out what to put in the photo!

**Comment by drpetrikov** [comment]
how about this one?
![Screenshot from 2024-07-27 22-46-01](https://github.com/user-attachments/assets/63986c99-36f0-422c-bee5-355fa1891f4a)
![icon](https://github.com/user-attachments/assets/efa5cfe7-6920-418b-91f1-6f9d660a3c59)

**Comment by fabiscafe** [comment]
![image](https://github.com/user-attachments/assets/890ab07a-d376-4440-b6cd-04b85d5f4645)

A bit more simple, while keeping my last idea.

**Comment by drpetrikov** [comment]
this is great!! can j have the svg?

**Comment by blissd** [comment]
>  A bit more simple, while keeping my last idea.

That looks very nice. However, I do think having a blue sky or sun rays and blue mountains causes the icon to lose clarity when it gets smaller. Do you think any other colour combinations would work?

**Comment by fabiscafe** [comment]
@blissd I think it works best with how it currently is. First I wanted some combination that fades into a "kind of solid colour" on smaller resolution. So that is basically appears as a blue blob with yellow dot.:
![grafik](https://github.com/user-attachments/assets/2b8d11e2-6278-4c95-b220-d43354e29dab)

But after I generated the 32px resolution I realized that the current one still have a lot of details in 32, and even in 16px resolution (We don't even use 16px, but the symbolic in that case). I think we're very fine with this:
![rect404](https://github.com/user-attachments/assets/74fe5d3e-0ce9-4f0c-980f-48213ac14972)
Here compared with Loupe.


-----

@drpetrikov Current one is in [my fork](https://github.com/fabiscafe/fotema/tree/app-icon/data/icons) (not finished, shadows very much need a bit of work). Please also test inside of [AppIconPreview](https://flathub.org/apps/org.gnome.design.AppIconPreview)

**Comment by blissd** [comment]
For comparison, here is your icon with some pinky-orange mountains.
![Screenshot from 2024-07-28 15-12-17](https://github.com/user-attachments/assets/f5a36be3-08c7-4c62-a0f5-a7fdca8e2692)

**Comment by fabiscafe** [comment]
I tried to be consistent to how real light works: 
![out](https://github.com/user-attachments/assets/25c3bbcb-2f6c-41f2-a9dd-eef78d652435)

I kind of understand what you try to do, but we have to find something that stays in an "abstraction of realism" to not look off and have a meaning iconology wise. Brighter things in front of the sun are also harder to see on smaller resolutions
![grafik](https://github.com/user-attachments/assets/d2706e35-0024-478f-8667-14f4d3cb36dc)

Let's brainstorm what else is possible :smile:

**Comment by blissd** [comment]
I see your point about how light would work. Here is the tones between the mountains and sun rays flipped.
![image](https://github.com/user-attachments/assets/d397d07f-3671-4388-94e4-ba1eb285d19a)

**Comment by drpetrikov** [comment]
how about a pet? brings some whimsy to the icon and the background could just be a solid colour or subtle gradient

**Comment by drpetrikov** [comment]
also @fabiscafe i'm not really sure about how you used images as a shadow, check out the icon for Errands, maybe that'll work better

**Comment by blissd** [comment]
I've had a go rotating the icon 90% anti-clockwise to put the thicker edge of the Polaroid photo at the bottom.
![image](https://github.com/user-attachments/assets/46acd181-bc79-44ae-96cf-843321fc3523)

**Comment by bertob** [comment]
I was wondering about a metaphor that's not so similar to image viewer icons. Maybe something like a photo book?

Here's a super quick experiment:

![image](https://github.com/user-attachments/assets/821140b2-d0a7-466a-9d95-62f78d229f84)

**Comment by fabiscafe** [comment]
@bertob  I actually like this direction a lot more. It's calm, simple and would solve the question on what to show in a picture frame :smile:. However I have some doubts. Many wont see the connection from a Photos app to a photo book, simply because they have never seen a photo book. Much like the floppy symbol as 'save to' icon. Do you think this could be a problem?

**Comment by CocolinoFan** [comment]
I like the photo book design as well. Maybe put vector graphics in the pictures inside on the photo book instead of colour gradients?
Maybe a selfie for the long picture, sunset for the small picture and a dogo for the medium one.

**Comment by drpetrikov** [comment]
@blissd So, is a new icon happening? Maybe even an intermediate one would be better than the current one that as you said, is blocking the app from being featured on Flathub.

**Comment by blissd** [comment]
Hi @drpetrikov. At some point I imagine it will, but I'm in no hurry.

**Comment by bertob** [comment]
Here's another attempt. I feel like it's a bit too detailed now maybe, I think overall I still prefer the simple gradients.

![image](https://github.com/user-attachments/assets/03ef9154-457f-4bef-b97e-09bcdf418438)

**Comment by blissd** [comment]
Looks great at 128x128, but does get a bit busy at smaller sizes. I had never realized icon design was so hard!

**Comment by CocolinoFan** [comment]
What bothers me is that Fotema is not really designed like a photo book. Is more like a continuous 
slide show of pictures, there are no pages to flip through.
How about an icon that represents that, a continuous slide show of pictures, like a film roll: [example 1](https://cdn.culture.ru/images/2674c470-d799-5aae-8b18-f187a9663b43), [example 2](https://www.stevendejongfilms.nl/wp-content/uploads/FIlmrol-3.jpg) and [example 3](https://i.pinimg.com/originals/5e/b6/96/5eb696a8dded4141a036646a08edd6d6.jpg)

**Comment by bertob** [comment]
Icon metaphors are not about capturing the functionality of the app exactly, but more about giving a general idea of the domain. A film reel would make it seem like it's a video app.

Personally I'd suggest moving forward with something like the simpler one for now just to bring it in line with the guidelines, we can always change it again later :)

**Comment by drpetrikov** [comment]
yeah, better to have a good icon and make it better later than a generic project one, also i love @bertob's work!

**Comment by blissd** [comment]
> Personally I'd suggest moving forward with something like the simpler one for now just to bring it in line with the guidelines, we can always change it again later :)

@bertob If you are willing to put together a PR I'll cut a new release. How would you license the icon?

**Comment by bertob** [comment]
Cool, yeah I can open an MR for this. I think usually icons the same license as the rest of the project, but whatever you prefer.

**Comment by blissd** [comment]
The licence of the current icons is GPL3 and is declared in the top-level [REUSE.toml](https://github.com/blissd/fotema/blob/main/REUSE.toml#L40) file. Feel free to update the copyright text to reference yourself if you wish.

**Comment by blissd** [comment]
> The licence of the current icons is GPL3 and is declared in the top-level [REUSE.toml](https://github.com/blissd/fotema/blob/main/REUSE.toml#L40) file. Feel free to update the copyright text to reference yourself if you wish.

Hmm... I see I've made a mistake there and have licenced the icons twice--once as GPL3 and once as CC0! I'm not sure what the best licence is for icons... but I think I'd lean towards one of the CC licences as they are an artistic work.

**Comment by blissd** [comment]
Thank you @bertob, @fabiscafe , and @drpetrikov for all your help with icons.
